---

- hosts: all
  become: true
  become_user: root
  become_method: sudo

  tasks:

   - name: apache installation and staring
     yum: name=httpd  state=present

   - name: start the service
     service: name=httpd state=started enabled=yes
     register: apache_stat

   - name: share the stat of apache start command
     debug: msg={{ apache_stat.stdout }}
   
 
