---

- hosts: all
  become: true
  become_user: root
  become_method: sudo

  tasks:

   - name: installation  
     yum:
       name={{ item  }}
       state=present 
     with_items:
       - epel-release
       - bind

   - name: service start
     service:
       name={{ item }}
       enabled=yes
       state=started
     with_items: 
       - bind 
