---
- hosts: all
  become_user: root 
  tasks:
    - name: Installs nginx web server
      yum: name=nginx state=installed update_cache=true
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx  state=stopped
      service: name=nginx  state=stopped
      service: name=nginx  state=stopped
      service: name=nginx  state=started

